const materiasPorAnio = {
  primerAnio: ["mb", "ic", "sr1", "if", "fi", "dcc", "ii", "f1", "c1", "sr2", "q", "co1"],
  segundoAnio: ["f2", "alga", "tmt", "co2", "i1", "f3", "c2", "et", "cm"],
  tercerAnio: ["edcn", "eb", "erm", "ss", "lmmee", "i2", "ed", "sm1", "mei", "iei"],
  cuartoAnio: ["est", "mr", "mc", "ti", "sc", "ai", "mem", "se", "r1", "ga"],
  quintoAnio: ["ep", "ia", "sm2", "sanh", "r2", "sorc", "ogi", "hsi", "pim"],
};

const primerCuatri = ["mb", "ic", "sr1", "if", "fi", "dcc", "ii","q"]

const data_a = {
  mb: [],
  ic: [],
  sr1: [],
  if: [],
  fi: [],
  dcc: [],
  ii: [],
  f1: ['if', 'mb'],
  c1: ['ic'],
  sr2: ['sr1'],
  q: [],
  co1: ['fi'],
  f2: ['f1', 'c1'],
  alga: ['mb'],
  tmt: ['if', 'ic', 'q'],
  co2: ['co1'],
  i1: ['dcc'],
  f3: ['f2'],
  c2: ['c1'],
  et: ['f2', 'c1'],
  cm: ['q'],
  edcn: ['c2'],
  eb: ['et'],
  erm: ['if', 'ic', 'cm'],
  ss: ['c2'],
  lmmee: ['et'],
  i2: ['i1'],
  ed: ['eb'],
  sm1: ['eb'],
  mei: ['et'],
  iei: ['et'],
  est: ['mb', 'c1'],
  mr: ['edcn', 'erm'],
  mc: ['co2', 'lmmee', 'ed'],
  ti: ['sr2', 'erm'],
  sc: ['co2', 'lmmee', 'ed', 'ss'],
  ai: ['ed'],
  mem: ['sr2', 'mr'],
  se: ['mc'],
  r1: ['mr', 'sc'],
  ga: ['ii', 'sm1'],
  ep: ['iei', 'mc'],
  ia: ['co2', 'edcn', 'est'],
  sm2: ['sm1', 'sc', 'ai'],
  sanh: ['sm1', 'mr'],
  r2: ['r1'],
  sorc: ['ss', 'ai', 'se'],
  ogi: ['est', 'ti'],
  hsi: ['mei', 'iei', 'ga'],
  pim: ['mb', 'ic', 'sr1', 'if', 'fi', 'dcc', 'ii', 'f1', 'c1', 'sr2', 'q', 'co1', 'f2', 'alga', 'tmt', 'co2', 'i1', 'f3', 'c2', 'et', 'cm', 'edcn', 'eb', 'erm', 'ss', 'lmmee', 'i2', 'ed', 'sm1', 'mei', 'iei', 'est', 'mr', 'mc', 'ti', 'sc', 'ai', 'mem', 'se', 'r1', 'ga', 'ep', 'ia', 'sm2', 'sanh', 'r2', 'sorc', 'ogi', 'hsi']
};

const data_r = {
  mb: [],
  ic: [],
  sr1: [],
  if: [],
  fi: [],
  dcc: [],
  ii: [],
  f1: [],
  c1: [],
  sr2: [],
  q: [],
  co1: [],
  f2: [],
  alga: [],
  tmt: [],
  co2: [],
  i1: [],
  f3: [],
  c2: [],
  et: [],
  cm: [],
  edcn: [],
  eb: [],
  erm: [],
  ss: [],
  lmmee: [],
  i2: [],
  ed: [],
  sm1: [],
  mei: [],
  iei: [],
  est: [],
  mr: [],
  mc: [],
  ti: [],
  sc: [],
  ai: [],
  mem: [],
  se: [],
  r1: [],
  ga: [],
  ep: [],
  ia: [],
  sm2: [],
  sanh: [],
  r2: [],
  sorc: [],
  ogi: [],
  hsi: [],
  pim: []
};

const data_cursar_a = {
  mb: [],
  ic: [],
  sr1: [],
  if: [],
  fi: [],
  dcc: [],
  ii: [],
  f1: [],
  c1: [],
  sr2: [],
  q: [],
  co1: [],
  f2: ['f1', 'c1'],
  alga: [],
  tmt: ['q', 'if', 'ic'],
  co2: [],
  i1: [],
  f3: [],
  c2: [],
  et: ['f2', 'c1'],
  cm: [],
  edcn: [],
  eb: [],
  erm: ['cm', 'if', 'ic'],
  ss: [],
  lmmee: [],
  i2: [],
  ed: [],
  sm1: [],
  mei: [],
  iei: [],
  est: ['c1', 'mb'],
  mr: ['erm', 'edcn'],
  mc: ['ed', 'lmmee', 'co2'],
  ti: ['erm', 'sr2'],
  sc: ['ss', 'ed', 'lmmee', 'co2'],
  ai: [],
  mem: ['mr', 'sr2'],
  se: [],
  r1: ['sc', 'mr'],
  ga: ['sm1', 'ii'],
  ep: ['mc', 'iei'],
  ia: ['est', 'edcn', 'co2'],
  sm2: ['ai', 'sc', 'sm1'],
  sanh: ['mr', 'sm1'],
  r2: [],
  sorc: ['se', 'ai', 'ss'],
  ogi: ['ti', 'est'],
  hsi: ['ga', 'iei', 'mei'],
  pim: []
};

const data_cursar_r = {
  mb: [],
  ic: [],
  sr1: [],
  if: [],
  fi: [],
  dcc: [],
  ii: [],
  f1: ['if', 'mb'],
  c1: ['ic'],
  sr2: ['sr1'],
  q: [],
  co1: ['fi'],
  f2: [],
  alga: ['mb'],
  tmt: [],
  co2: ['co1'],
  i1: ['dcc'],
  f3: ['f2'],
  c2: ['c1'],
  et: [],
  cm: ['q'],
  edcn: ['c2'],
  eb: ['et'],
  erm: [],
  ss: ['c2'],
  lmmee: ['et'],
  i2: ['i1'],
  ed: ['eb'],
  sm1: ['eb'],
  mei: ['et'],
  iei: ['et'],
  est: [],
  mr: [],
  mc: [],
  ti: [],
  sc: [],
  ai: ['ed'],
  mem: [],
  se: ['mc'],
  r1: [],
  ga: [],
  ep: [],
  ia: [],
  sm2: [],
  sanh: [],
  r2: ['r1'],
  sorc: [],
  ogi: [],
  hsi: [],
  pim: []
};
