const materiasPorAnio = {
  primerAnio: ["mb","ic","q1","dcc","idp","c1","fi","sr","q2"],
  segundoAnio: ["f1","alga","iqo","bio","qa","pt1","c2","f2","qo1","mg"],
  tercerAnio: ["qo2","tia","ter","ma","pt2","i1","edcn","qba","fq","ft","ppst"],
  cuartoAnio: ["scsp","est","ou1","pt3","i2","ifh","ou2","ts"],
  quintoAnio: ["tpi","pfa","il","biote","pa","econ","hsi","icarn","acca","sga"],
}

const primerCuatri = ["mb","ic","q1","dcc", "idp", "fi","sr"]

const data_a = { 
  mb: [],
  ic: [],
  q1: [],
  dcc: [],
  idp: [],
  c1: ['ic'],
  fi: [],
  sr: [],
  q2: ['q1'],
  f1: ['mb'],
  alga: ['mb'],
  iqo: ['q1'],
  bio: ['q1'],
  qa: ['q2'],
  pt1: [],
  c2: ['c1'],
  f2: ['f1'],
  qo1: ['alga'],
  mg: ['iqo','bio'],
  qo2: ['qo1'],
  tia: ['q2','qa'],
  ter: ['f1'],
  ma: ['mg'],
  pt2: ['alga','qa'],
  i1: ['dcc'],
  edcn: ['alga','c2'],
  qba: ['qo2','q2'],
  fq: ['ter'],
  ft: ['ter'],
  ppst: ['mb','ic','q1','dcc','idp','c1','fi','sr','q2','f1','alga','iqo','bio','qa','pt1','c2','f2','qo1','mg','qo2','tia','ter','ma','pt2','i1','edcn','qba','fq','ft'],
  scsp: ['f2','c1','f1'],
  est: ['mb','c1'],
  ou1: ['ft'],
  pt3: ['bio'],
  i2: ['i1'],
  ifh: ['qba'],
  ou2: ['fq','ft'],
  ts: ['f1'],
  tpi: ['mb','ic','q1','dcc','idp','c1','fi','sr','q2','f1','alga','iqo','bio','qa','pt1','c2','f2','qo1','mg','qo2','tia','ter','ma','pt2','i1','edcn','qba','fq','ft','scsp','est','ou1','pt3','i2','ifh','ou2','ts','pfa','il','biote','pa','econ','hsi','icarn','acca','sga'],
  pfa: ['ft','qo2'],
  il: ['ou2','ou1','qba','ma'],
  biote: ['qba','mg'],
  pa: ['ou1'],
  econ: [],
  hsi: ['ts'],
  icarn: ['ou1','pt3','ou2','pfa'],
  acca: ['est','ma'],
  sga: ['ou1','ts'],
}

const data_cursar_a = { 
  mb: [],
  ic: [],
  q1: [],
  dcc: [],
  idp: [],
  c1: [],
  fi: [],
  sr: [],
  q2: [],
  f1: [],
  alga: [],
  iqo: ['q1'],
  bio: ['q1'],
  qa: [],
  pt1: [],
  c2: ['mb', 'ic'],
  f2: [],
  qo1: [],
  mg: [],
  qo2: ['iqo'],
  tia: ['q1'],
  ter: ['q1'],
  ma: [],
  pt2: ['iqo', 'bio'],
  i1: ['dcc'],
  edcn: [],
  qba: ['qo2'],
  fq: ['q1', 'f1'],
  ft: ['f2'],
  ppst: ['mb','ic','q1','dcc','idp','c1','fi','sr','q2','f1','alga','iqo','bio','qa','pt1','c2','f2','qo1','mg','qo2','tia','ter','ma','pt2','i1','edcn','qba','fq','ft'],
  scsp: ['c1', 'f1'],
  est: ['mb', 'c1'],
  ou1: ['ter'],
  pt3: ['bio'],
  i2: ['i1'],
  ifh: ['qa'],
  ou2: ['fq', 'ft'],
  ts: ['f1'],
  tpi: ['mb','ic','q1','dcc','idp','c1','fi','sr','q2','f1','alga','iqo','bio','qa','pt1','c2','f2','qo1','mg','qo2','tia','ter','ma','pt2','i1','edcn','qba','fq','ft','scsp','est','ou1','pt3','i2','ifh','ou2','ts','pfa','il','biote','pa','econ','hsi','icarn','acca','sga'],
  pfa: ['ft', 'qo2'],
  il: ['ou2', 'ou1', 'qba', 'ma'],
  biote: ['qba', 'mg'],
  pa: ['ou1'],
  econ: [],
  hsi: ['ts'],
  icarn: ['ou1', 'pt3', 'ou2', 'pfa'],
  acca: ['est', 'ma'],
  sga: ['ou1', 'ts']
}

const data_r = { 
  mb: [],
  ic: [],
  q1: [],
  dcc: [],
  idp: [],
  c1: [],
  fi: [],
  sr: [],
  q2: [],
  f1: ['ic','c1'],
  alga: [],
  iqo: [],
  bio: [],
  qa: [],
  pt1: ['idp'],
  c2: ['alga'],
  f2: [],
  qo1: [],
  mg: [],
  qo2: [],
  tia: [],
  ter: [],
  ma: [],
  pt2: ['mg'],
  i1: [],
  edcn: [],
  qba: [],
  fq: [],
  ft: ['alga'],
  ppst: [],
  scsp:['edcn','ft'],
  est: [],
  ou1: [],
  pt3: ['qba'],
  i2: [],
  ifh: ['ma','ou1'],
  ou2: [],
  ts: ['ft'],
  tpi: [],
  pfa: [],
  il: [],
  biote: [],
  pa: [],
  econ: ['est'],
  hsi: [],
  icarn: ['pa'],
  acca: ['ou2'],
  sga: ['biote'],
}

const data_cursar_r = { 
  mb: [],
  ic: [],
  q1: [],
  dcc: [],
  idp: [],
  c1: ['ic'],
  fi: [],
  sr: [],
  q2: ['q1'],
  f1: ['mb', 'ic', 'c1'],
  alga: ['mb'],
  iqo: [],
  bio: [],
  qa: ['q2'],
  pt1: ['idp'],
  c2: ['alga', 'c1'],
  f2: ['f1'],
  qo1: ['alga'],
  mg: ['iqo', 'bio'],
  qo2: ['qo1'],
  tia: ['qa', 'f2'],
  ter: ['f1'],
  ma: ['mg'],
  pt2: ['mg'],
  i1: [],
  edcn: ['c2'],
  qba: ['q2'],
  fq: ['ter'],
  ft: ['alga', 'c2', 'ter'],
  ppst: [],
  scsp: ['edcn', 'ft'],
  est: [],
  ou1: ['ft'],
  pt3: ['qba'],
  i2: [],
  ifh: ['ma', 'ou1'],
  ou2: [],
  ts: ['ft'],
  tpi: [],
  pfa: [],
  il: [],
  biote: [],
  pa: [],
  econ: ['est'],
  hsi: [],
  icarn: ['pa'],
  acca: ['ou2'],
  sga: ['biote']
}
