const materiasPorAnio = {
  primerAnio: ["mb", "ic", "sr1", "if", "fi", "dcc", "ii", "f1", "c1", "sr2", "q", "co1"],
  segundoAnio: ["f2", "alga", "tmt", "co2", "i1", "et", "cm", "mi"],
  tercerAnio: ["eb", "lmmee", "ed", "sm1", "mei", "est"],
};

const primerCuatri = ["mb", "ic", "sr1", "if", "fi", "dcc", "ii","q"]

const data_a = {
  mb: [],
  ic: [],
  sr1: [],
  if: [],
  fi: [],
  dcc: [],
  ii: [],
  f1: ['mb', 'if'],
  c1: ['ic'],
  sr2: ['sr1'],
  q: [],
  co1: ['fi'],
  f2: ['f1', 'c1'],
  alga: ['mb'],
  tmt: ['ic', 'f1', 'q'],
  co2: ['co1'],
  i1: ['dcc'],
  et: ['c1', 'f2'],
  cm: ['q'],
  mi: ['mb','if'],
  eb: ['et'],
  lmmee: ['et'],
  ed: ['eb'],
  sm1: ['eb'],
  mei: ['et'],
  est: ['mb', 'c1']
};

const data_r = {
  mb: [],
  ic: [],
  sr1: [],
  if: [],
  fi: [],
  dcc: [],
  ii: [],
  f1: ['mb', 'if'],
  c1: ['ic'],
  sr2: ['sr1'],
  q: [],
  co1: ['fi'],
  f2: ['f1', 'c1'],
  alga: ['mb'],
  tmt: ['ic', 'f1', 'q'],
  co2: ['co1'],
  i1: ['dcc'],
  et: ['c1', 'f2'],
  cm: ['q'],
  mi: ['mb','if'],
  eb: ['et'],
  lmmee: ['et'],
  ed: ['eb'],
  sm1: ['eb'],
  mei: ['et'],
  est: ['mb', 'c1']
};

const data_cursar_a = {
  mb: [],
  ic: [],
  sr1: [],
  if: [],
  fi: [],
  dcc: [],
  ii: [],
  f1: ['mb', 'if'],
  c1: ['ic'],
  sr2: ['sr1'],
  q: [],
  co1: ['fi'],
  f2: ['f1', 'c1'],
  alga: ['mb'],
  tmt: ['ic', 'f1', 'q'],
  co2: ['co1'],
  i1: ['dcc'],
  et: ['c1', 'f2'],
  cm: ['q'],
  mi: ['mb','if'],
  eb: ['et'],
  lmmee: ['et'],
  ed: ['eb'],
  sm1: ['eb'],
  mei: ['et'],
  est: ['mb', 'c1']
};

const data_cursar_r = {
  mb: [],
  ic: [],
  sr1: [],
  if: [],
  fi: [],
  dcc: [],
  ii: [],
  f1: ['mb', 'if'],
  c1: ['ic'],
  sr2: ['sr1'],
  q: [],
  co1: ['fi'],
  f2: ['f1', 'c1'],
  alga: ['mb'],
  tmt: ['ic', 'f1', 'q'],
  co2: ['co1'],
  i1: ['dcc'],
  et: ['c1', 'f2'],
  cm: ['q'],
  mi: ['mb','if'],
  eb: ['et'],
  lmmee: ['et'],
  ed: ['eb'],
  sm1: ['eb'],
  mei: ['et'],
  est: ['mb', 'c1']
};
