const materiasPorAnio = {
  primerAnio: ["mkt", "q", "mat", "igg", "adm", "i", "gg1", "tbc", "ma", "hsa", "co"],
  segundoAnio: ["tac", "inf", "cca", "gg2", "nut", "gi", "cos", "rp", "ecp", "egs", "pps"]
}

const data_a = { 
  mkt: [],
  q: [],
  mat: [],
  igg: [],
  adm: [],
  i: [],
  gg1: [],
  tbc: [],
  ma: [],
  hsa: [],
  co: [],
  tac: [],
  inf: [],
  cca: [],
  gg2: ['adm', 'gg1'],
  nut: ['hsa'],
  gi: ['tbc', 'nut'],
  cos: ['inf', 'gg2'],
  rp: ['cca'],
  ecp: ['co'],
  egs: ['co', 'gg2'],
  pps: ['mkt','q','mat','igg','adm','i','gg1','tbc','ma','hsa','co','tac','inf','cca','gg2','nut','gi','cos','rp','ecp','egs']
}

const data_cursar_a = { 
  mkt: [],
  q: [],
  mat: [],
  igg: [],
  adm: [],
  i: [],
  gg1: [],
  tbc: [],
  ma: [],
  hsa: [],
  co: [],
  tac: ['igg'],
  inf: [],
  cca: [],
  gg2: ['adm', 'gg1'],
  nut: ['q', 'hsa'],
  gi: ['tbc', 'hsa', 'nut'],
  cos: ['tbc', 'ma'],
  rp: ['ma', 'hsa'],
  ecp: ['co'],
  egs: ['co', 'gg2'],
  pps: ['mkt','q','mat','igg','adm','i','gg1','tbc','ma','hsa','co','tac','inf','cca','gg2','nut','gi','cos','rp','ecp','egs']
}

const data_r = { 
  mkt: [],
  q: [],
  mat: [],
  igg: [],
  adm: [],
  i: [],
  gg1: ['mat', 'igg', 'adm'],
  tbc: ['q', 'igg'],
  ma: ['q', 'mat'],
  hsa: [],
  co: ['mkt', 'adm'],
  tac: ['tbc'],
  inf: ['mat'],
  cca: ['tbc', 'ma'],
  gg2: ['co', 'tac'],
  nut: ['hsa'],
  gi: ['tbc', 'nut'],
  cos: ['inf', 'gg2'],
  rp: ['cca'],
  ecp: ['co'],
  egs: ['co', 'gg2'],
  pps: []
}

const data_cursar_r = { 
  mkt: [],
  q: [],
  mat: [],
  igg: [],
  adm: [],
  i: [],
  gg1: [],
  tbc: [],
  ma: [],
  hsa: [],
  co: [],
  tac: ['igg'],
  inf: [],
  cca: [],
  gg2: ['adm', 'gg1'],
  nut: ['q', 'hsa'],
  gi: ['tbc', 'hsa', 'nut'],
  cos: ['tbc', 'ma'],
  rp: ['ma', 'hsa'],
  ecp: ['co'],
  egs: ['co', 'gg2'],
  pps: []
}
